const jobData = [
  {
    id: 1,
    title: 'Frontend Developer',
    company: 'SparkCode',
    location: 'Remote',
    type: 'Full-Time',
    salary: '$60k - $75k',
    logo: 'SC',
    category: 'IT',
  },
  {
    id: 2,
    title: 'Marketing Intern',
    company: 'GrowthRise',
    location: 'New York, NY',
    type: 'Internship',
    salary: '$18/hr',
    logo: 'GR',
    category: 'Marketing',
  },
  {
    id: 3,
    title: 'UX Designer',
    company: 'NuVista Labs',
    location: 'Austin, TX',
    type: 'Full-Time',
    salary: '$55k - $70k',
    logo: 'NU',
    category: 'Design',
  },
  {
    id: 4,
    title: 'Financial Analyst',
    company: 'Finova',
    location: 'Chicago, IL',
    type: 'Full-Time',
    salary: '$65k - $80k',
    logo: 'FI',
    category: 'Finance',
  },
  {
    id: 5,
    title: 'Sales Associate Intern',
    company: 'TrendZone',
    location: 'San Francisco, CA',
    type: 'Internship',
    salary: '$20/hr',
    logo: 'TZ',
    category: 'Sales',
  },
  {
    id: 6,
    title: 'Data Analyst',
    company: 'Vanta Networks',
    location: 'Remote',
    type: 'Full-Time',
    salary: '$70k - $85k',
    logo: 'VN',
    category: 'IT',
  },
  {
    id: 7,
    title: 'Content Strategist',
    company: 'Luma Media',
    location: 'Remote',
    type: 'Full-Time',
    salary: '$52k - $65k',
    logo: 'LM',
    category: 'Marketing',
  },
  {
    id: 8,
    title: 'HR Coordinator',
    company: 'Orbit Works',
    location: 'Boston, MA',
    type: 'Full-Time',
    salary: '$50k - $62k',
    logo: 'OW',
    category: 'Sales',
  },
  {
    id: 9,
    title: 'Graphic Designer',
    company: 'Crest Studio',
    location: 'Los Angeles, CA',
    type: 'Internship',
    salary: '$19/hr',
    logo: 'CS',
    category: 'Design',
  },
  {
    id: 10,
    title: 'Product Marketing Manager',
    company: 'Axiom Labs',
    location: 'Seattle, WA',
    type: 'Full-Time',
    salary: '$80k - $95k',
    logo: 'AL',
    category: 'Marketing',
  },
  {
    id: 11,
    title: 'Junior Accountant',
    company: 'Pulse Ventures',
    location: 'Miami, FL',
    type: 'Full-Time',
    salary: '$48k - $56k',
    logo: 'PV',
    category: 'Finance',
  },
  {
    id: 12,
    title: 'UX Research Intern',
    company: 'Nova Systems',
    location: 'Remote',
    type: 'Internship',
    salary: '$22/hr',
    logo: 'NS',
    category: 'Design',
  },
];
